server:
  port: 8082
spring:
  application:
    name: dubbo-mock-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mock?serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123$qwerasdf

  mvc:
    staticPathPattern: classpath:/static/
  freemarker:
    charset: UTF-8
    suffix:
    contentType: text/html
    templateLoaderPath: classpath:/templates/


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.entity

